version: '3.8'

services:
  frontend:
    build: ../frontend
    command: sleep infinity
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/work/

  backend:
    build: ../backend
    command: sleep infinity
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/work/

  elasticsearch:
    image: elasticsearch:8.7.1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch:
