on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - name: Create PR
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        title: MERGE main TO releases
        assignee: ${{ github.actor }}
        body: "**ATUOMATED PULL REQUEST. DO NOT REBASE AND MERGE OR SQUASH MERGE!!!**"
        target_branch: releases 
