on:
    workflow_dispatch:
    schedule:
        - cron:  '0 4 * * *'
jobs:
    merge-main:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
              with:
                ref: main
                fetch-depth: 0
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5.0.1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: MERGE main TO releases
                assignees: ${{ github.actor }}
                reviewers: steven9909, JBennyHuang
                body: "**ATUOMATED PULL REQUEST. DO NOT SQUASH MERGE OR MERGE COMMIT!!!**"
                branch: releases
                delete-branch: false
                draft: false
